# --- Grid Config ---

WIDTH = 320
HEIGHT = 240
CELL_SIZE = 40
MARK_SIZE = 20
GRID_WIDTH = WIDTH // CELL_SIZE
GRID_HEIGHT = HEIGHT // CELL_SIZE

# --- Game Config ---

SHOW_GAME_RENDER = False
MODEL = 1  # 1 -> MAAC | 2 -> MAPPO

# --- Environment Config ---

ROBOT_NUMBER = 2
ROBOT_COLORS = [(255, 0, 0), (0, 255, 0), (0, 0, 255)]
OBSTACLE_COLOR = (200, 200, 200)
OBSTACLE_PROBABILITY = 0.05
FPS = 30

# --- Save Config ---

SAVE_FOLDER = "./training_data"
SAVE_PATH = f"{SAVE_FOLDER}/model_maac.pth" if MODEL == 1 else f"{SAVE_FOLDER}/model_mappo.pth"
SAVE_MODEL_EVERY = 50

# --- Global Train Config ---
MAX_EPISODES = 1000
MAX_STEPS = 200
LR_ACTOR = 0.0001
LR_CRITIC = 0.0005
GAMMA = 0.99

# --- Train Config MAAC ---

NN_INPUT_SIZE = (WIDTH // CELL_SIZE) * (HEIGHT // CELL_SIZE) + ROBOT_NUMBER * 2
BUFFER_SIZE = 50000
BATCH_SIZE = 256
UPDATES_PER_EPISODE_COLLECTION = 4
TAU = 0.001
GUMBEL_TEMPERATURE = 0.8
EPSILON_START = 1.0
EPSILON_DECAY = 0.995
EPSILON_MIN = 0.05
CLIP_GRAD_NORM = 1.0

# --- Train Config MAPPO ---
ROLLOUT_LENGTH = 128
PPO_EPOCHS = 4
PPO_MINIBATCH_SIZE = 32
PPO_CLIP_EPS = 0.2
GAE_LAMBDA = 0.95
ENTROPY_COEFF = 0.007
VALUE_LOSS_COEFF = 0.5
MAX_GRAD_NORM = 0.5
